name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tooling and use Rust cache
        uses: ./.github/actions/rust-cache
      - run: cargo fmt --all --check
      - run: cargo check -p example --target=riscv32i-unknown-none-elf
      - run: cargo check --bins --examples --tests --benches --all-features

  cargo-test:
    needs: check-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tooling and use Rust cache
        uses: ./.github/actions/rust-cache
      - run: cargo test --bins --examples --all-features

  test-smoke:
    needs: check-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tooling and use Rust cache
        uses: ./.github/actions/rust-cache
      - run: assets/scripts/smoke.sh examples/src/bin/fib3_profiling.rs
      - run: assets/scripts/smoke.sh examples/src/bin/hello.rs

  test-sdk:
    needs: check-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tooling and use Rust cache
        uses: ./.github/actions/rust-cache
      - run: assets/scripts/test_sdk.sh examples/src/bin/hello.rs

  detect-unused-crate:
    runs-on: ubuntu-latest
    steps:
      - uses: bnjbvr/cargo-machete@main
